version: '3.5'

services:
  
  mnotes_db:
    image: postgres:9.6
    restart: always
    container_name: mnotes_db
    environment:
      POSTGRES_DB: mnotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  test_db:
    image: postgres:9.6
    restart: always
    container_name: test_db
    environment:
      POSTGRES_DB: mnotes
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    ports:
      - 5439:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always